name = "mpd-multi-poi"
uuid = "00000000-0000-4000-8000-000000000001"
version = "0.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OpenDSSDirect = "a8b11937-1041-50f2-9818-136bb7a8fb06"

[compat]
julia = "1"
